PartialViewEg/Models/Student.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PartialViewEg.Models
{
    [Bind(Exclude ="name")]
    public class Student
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Job { get; set; }
    }
}

PartialViewEg/Controllers/StudentController.cs
using PartialViewEg.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PartialViewEg.Controllers
{
    public class StudentController : Controller
    {
        // GET: Student
        public ActionResult Index()
        {
            return View();
           
        }

        public ActionResult check()
        {
            List<Student> studlist = GetStudent();
            return PartialView("Student_Partial", studlist);

        }
        [HttpGet]
        public ActionResult create()
        {
            Student s = new Student();
            UpdateModel(s);

            return View();

        }
        [HttpPost]
        public ActionResult create(Student s)
        {
            //Student s = new Student();
            //UpdateModel(s);

            return View();

        }

        private List<Student> GetStudent()
        {
            SqlConnection con = new SqlConnection("Data Source=SUYPC223;Initial Catalog=DbDatabase;Integrated Security=True");
            con.Open();
            SqlDataAdapter ad = new SqlDataAdapter("select * from [dbo].[Student]", con);
            DataTable dt = new DataTable();
            ad.Fill(dt);
            List<Student> studlist = new List<Student>();
            foreach(DataRow dr in dt.Rows)
            {
                Student model = new Student();
                model.id = Convert.ToInt32(dr["id"]);
                model.Name = Convert.ToString(dr["Name"]);
                model.Job = Convert.ToString(dr["Job"]);
                studlist.Add(model);
            }
            return studlist;
       }

        
    }
}

PartialViewEg/Views/Shared/Student_Partial.cshtml
@model IEnumerable<PartialViewEg.Models.Student>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<div>Partial View</div>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Job)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Job)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>

PartialViewEg/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

PartialViewEg/Views/Student/Index.cshtml
@model IEnumerable<PartialViewEg.Models.Student>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<script src="~/scripts/jquery-1.10.2.js"></script>

<div>
    @*@{Html.RenderPartial("Student_Partial", Model);}*@
    @*@Html.Partial("Student_Partial", Model);*@

    <script type="text/javascript">
        $(document).ready(function(){
            $("#Button1").click(function(){
                $.ajax({
                    url:'@Url.Action("check", "Student")',
                    type:"GET",
                    success:function(data){
                    $('#container').html(data)
                     }
                     })
               });
             });
                         
    </script>

  
    
    <input id="Button1" type="button" value="button" />
</div>

<div id="container">



</div>

PartialViewEg/Views/Student/check.cshtml
@model IEnumerable<PartialViewEg.RouteConfig>

@{
    ViewBag.Title = "check";
}

<h2>check</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>

PartialViewEg/Views/Student/create.cshtml
@model PartialViewEg.Models.Student

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>create</title>
</head>
<body>
    @*@Html.Partial("Student_Partial", Model);*@
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Student</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Job, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Job, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Job, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")

    </div>
</body>
</html>